### PR TITLE
Update BEL exporter

### PR DESCRIPTION
**Pull request by cthoyt**
There were some changes that were made but not reflected in the BEL exporter script. this updates them. Since you weren't hosting a copy of the BEL export, I also made one and added it to the readme.

### CODE REVIEW

**Comment by nomisto** [comment]
Would it be a good idea to include the BEL export also on zenodo?

**Comment by matthias-samwald** [comment]
Yeah, please add to Zenodo!

**Comment by cthoyt** [comment]
@nomisto @matthias-samwald great, if you guys can take care of that then I don't need to have an additional repo

**Comment by nomisto** [comment]
@cthoyt @matthias-samwald I've added the files to zenodo, sorry for hosting them not earlier.

**Pull request merged**
